### ISSUE TITLE
Now broken as of Discourse 2.5.0.beta2

### ISSUE THREAD

**Issue by hifihedgehog** [cpradio/discourse-plugin-vb-emoticons#1]
See above. This great plugin has worked for years, but is now broken with Discourse 2.5.0.beta2.

**Comment by cpradio** [comment]
Fixed with #2

**Comment by hifihedgehog** [comment]
Thanks. Still not building for me with this latest release. :(
